return {
    "All Hail Sophia.",
    "All Hail Noire.",
    "Ganyu, my mother.",
    "Yes, that Noire. The Neptunia one.",
    "Pretty black theme, right? It's in the name!",
    "Make sure to eat healthily.",
    "Might it be time for a water break?",
    "Be sure to go and get some sunlight!",
    "Remember to commit your changes once in a while. Pushing even moreso.",
    "StackOverflow is your best friend; except for when it's not.",
    "Oh, the sun's out. When did that happen?",
    "May Rex Lapis watch over you. May your dreams be peaceful and sweet.",
    "Born of ice and frost.",
    "Access denied.",
    "No touching!",
    "All hail!",
    "Glaze over!",
    "This is long overdue!",
    "Healthy body, healthy mind!",
    "For Rex Lapis!",
    "If you lie on the grass, you can feel the heartbeat of the world.",
    "Ah, I love the smell of Glaze Lilies.",
    "How do I use a semicolon?",
    "Visual Studio Code but for intellectuals.",
    "VI: Improved.",
    "WEEB ♥ VIM",
    "I spent two days making this configuration.",
    "This was not the best use of my time.",
    "Hope you enjoy!",
    "Get ready!",
    "Captain Kidd!",
    "Saiten Taisei!",
    "Arsene!",
    "Satanael!",
    "Carmen!",
    "Hecate!",
    "Goemon!",
    "Zorro!",
    "Mercurius!",
    "Johanna!",
    "Anat!",
    "Necronomicon!",
    "Prometheus!",
    "Robin Hood!",
    "Loki!",
    "Gorokichi!",
    "Milady!",
    "Astarte!",
    "Pithos!",
    "Pandora!",
    "Whip 'em, Captain!",
    "Go down!",
    "Make sure to take breaks once in a while!",
    "Programming since 1976.",
    "\"The phantom thieves are the best thieves in the job.\"",
    "Take Your Heart",
    "Take Your Time",
    "Your dreams are much more complex than you think.",
    "\"Don't get all cocky because I normally behave myself. I am done playing nice!\"",
    "\"Don't take me too lightly! I can ruin your day in an instant.\"",
    "\"I realized that personal relationships are something to be treasured.\"",
    "Who's the high lord?",
    "\"I am Sophia, humanity's companion.\"",
    "\"I am not your doll anymore!\"",
    "\"This is the power of my heart!\""
}
